# Generated by Django 3.2.5 on 2021-07-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('is_private', models.BooleanField(blank=True, null=True)),
                ('is_verified', models.BooleanField(blank=True, null=True)),
                ('has_anonymous_profile_picture', models.BooleanField(blank=True, null=True)),
                ('biography', models.CharField(blank=True, max_length=500, null=True)),
                ('can_link_entities_in_bio', models.BooleanField(blank=True, null=True)),
                ('biography_with_entities', models.JSONField(blank=True, null=True)),
                ('external_url', models.CharField(blank=True, max_length=500, null=True)),
                ('reel_auto_archive', models.CharField(blank=True, max_length=500, null=True)),
                ('show_conversion_edit_entry', models.BooleanField(blank=True, null=True)),
                ('allowed_commenter_type', models.CharField(blank=True, max_length=500, null=True)),
                ('is_business', models.BooleanField(blank=True, null=True)),
                ('account_type', models.BigIntegerField(blank=True, null=True)),
                ('professional_conversion_suggested_account_type', models.BigIntegerField(blank=True, null=True)),
                ('is_call_to_action_enabled', models.BooleanField(blank=True, null=True)),
                ('personal_account_ads_page_name', models.CharField(blank=True, max_length=500, null=True)),
                ('personal_account_ads_page_id', models.CharField(blank=True, max_length=500, null=True)),
                ('account_badges', models.JSONField(blank=True, null=True)),
                ('fbid_v2', models.BigIntegerField(blank=True, null=True)),
                ('is_muted_words_global_enabled', models.BooleanField(blank=True, null=True)),
                ('is_muted_words_custom_enabled', models.BooleanField(blank=True, null=True)),
                ('birthday', models.CharField(blank=True, max_length=500, null=True)),
                ('biography_product_mentions', models.JSONField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.BigIntegerField(blank=True, null=True)),
                ('custom_gender', models.CharField(blank=True, max_length=500, null=True)),
                ('trusted_username', models.CharField(blank=True, max_length=500, null=True)),
                ('trust_days', models.BigIntegerField(blank=True, null=True)),
                ('profile_edit_params', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
