# Generated by Django 3.2.5 on 2021-07-26 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookies',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instagram.account'),
        ),
        migrations.AddField(
            model_name='cookies',
            name='authorization_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cookies',
            name='cookies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cookies',
            name='country',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cookies',
            name='device_settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cookies',
            name='last_login',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cookies',
            name='locale',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cookies',
            name='user_agent',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cookies',
            name='uuids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
