# Generated by Django 3.2.5 on 2021-07-26 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20210726_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='instagram.account')),
                ('customer', models.BigIntegerField(blank=True, null=True)),
                ('age', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cookies',
            name='last_login',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
