# Generated by Django 3.2.5 on 2021-07-26 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20210726_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookies',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='instagram.account'),
        ),
    ]
